name: Github Pagesへのデプロイ
on:
  push:
    tags:
      - "ver*"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリへチェックアウト
        uses: actions/checkout@v4
      - name: 最新タグの取得
        id: get_latest_tag
        run: echo "VERSION=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: タグ表示
        id: display_tag
        run: printf '%s\n' "$VERSION"
      - name: ライブラリのインストールとビルド
        env:
          VERSION: ${{ env.VERSION }}
        uses: withastro/action@v3
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: デプロイ
        id: deployment
        uses: actions/deploy-pages@v4