name: Github Pagesへのデプロイ
on:
  push:
    branchies: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリへチェックアウト
        uses: actions/checkout@v4
      - name: ライブラリのインストールとビルド
        uses: withastro/action@v3
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: デプロイ
        id: deployment
        uses: actions/deploy-pages@v4